import React, {useEffect} from 'react'
import { Link } from 'react-router-dom'
import { useTitle } from '../../hooks/useTitle'

function Privacypolicy() {
  useTitle("Privacy Policy")
          useEffect(()=>{
            window.scrollTo(0,0)
        })
  return (
    <> 
      
        <div className="section-container px-8 sm:px-14 md:px-28 my-20">
            
        <h1 className="text-3xl font-bold my-4">Privacy Policy</h1>



        <p>Last updated: September 02, 2023</p>



        <p>This Privacy Policy describes Our policies and procedures on the collection,use and disclosure of Your information when You use the Service and tells Youabout Your privacy rights and how the law protects You.</p>



        <p>We use Your Personal data to provide and improve the Service. By using theService, You agree to the collection and use of information in accordance withthis Privacy Policy.</p>



        <h1 className="text-3xl font-bold my-4">Interpretation and Definitions</h1>



        <h2 className="text-2xl font-semibold my-3">Interpretation</h2>



        <p>The words of which the initial letter is capitalized have meanings definedunder the following conditions. The following definitions shall have the samemeaning regardless of whether they appear in singular or in plural.</p>



        <h2 className="text-2xl font-semibold my-3">Definitions</h2>



        <p>For the purposes of this Privacy Policy:</p>



        <ul>
        <li>Account means a unique account created for You to access our Service orparts of our Service.</li>



        <li>Affiliate means an entity that controls, is controlled by or is undercommon control with a party, where “control” means ownership of 50% ormore of the shares, equity interest or other securities entitled to votefor election of directors or other managing authority.</li>



        <li>Company (referred to as either “the Company”, “We”, “Us” or “Our” in thisAgreement) refers to infrafoam industry, Ho.551, Pl. 1., Opp. ShubhResidency, Vav Jokha Road, Kamrej, Surat (394185) Gujarat..</li>



        <li>Cookies are small files that are placed on Your computer, mobile device orany other device by a website, containing the details of Your browsinghistory on that website among its many uses.</li>



        <li>Country refers to: Gujarat, India</li>



        <li>Device means any device that can access the Service such as a computer, acellphone or a digital tablet.</li>



        <li>Personal Data is any information that relates to an identified oridentifiable individual.</li>



        <li>Service refers to the Website.</li>



        <li>Service Provider means any natural or legal person who processes the dataon behalf of the Company. It refers to third-party companies orindividuals employed by the Company to facilitate the Service, to providethe Service on behalf of the Company, to perform services related to theService or to assist the Company in analyzing how the Service is used.</li>



        <li>Usage Data refers to data collected automatically, either generated by theuse of the Service or from the Service infrastructure itself (for example,the duration of a page visit).</li>



        <li>Website refers to infrafoam, accessible from <Link href="https://infrafoam.in/">https://infrafoam.in/</Link></li>



        <li>You means the individual accessing or using the Service, or the company,or other legal entity on behalf of which such individual is accessing orusing the Service, as applicable.</li>
        </ul>



        <h1 className="text-3xl font-bold my-4">Collecting and Using Your Personal Data</h1>



        <h2 className="text-2xl font-semibold my-3">Types of Data Collected</h2>



        <p>Personal Data</p>



        <div className="wp-block-code"><p>While using Our Service, We may ask You to provide Us with certain personally
        identifiable information that can be used to contact or identify You.
        Personally identifiable information may include, but is not limited to:

          * Usage Data

        Usage Data  
        ~~~~~~~~~~

        Usage Data is collected automatically when using the Service.

        Usage Data may include information such as Your Device's Internet Protocol
        address (e.g. IP address), browser type, browser version, the pages of our
        Service that You visit, the time and date of Your visit, the time spent on
        those pages, unique device identifiers and other diagnostic data.

        When You access the Service by or through a mobile device, We may collect
        certain information automatically, including, but not limited to, the type of
        mobile device You use, Your mobile device unique ID, the IP address of Your
        mobile device, Your mobile operating system, the type of mobile Internet
        browser You use, unique device identifiers and other diagnostic data.

        We may also collect information that Your browser sends whenever You visit our
        Service or when You access the Service by or through a mobile device.

        Tracking Technologies and Cookies  </p></div>







        <p>We use Cookies and similar tracking technologies to track the activity on OurService and store certain information. Tracking technologies used are beacons,tags, and scripts to collect and track information and to improve and analyzeOur Service. The technologies We use may include:</p>



        <ul>
        <li>Cookies or Browser Cookies. A cookie is a small file placed on YourDevice. You can instruct Your browser to refuse all Cookies or to indicatewhen a Cookie is being sent. However, if You do not accept Cookies, Youmay not be able to use some parts of our Service. Unless you have adjustedYour browser setting so that it will refuse Cookies, our Service may useCookies.</li>



        <li>Web Beacons. Certain sections of our Service and our emails may containsmall electronic files known as web beacons (also referred to as cleargifs, pixel tags, and single-pixel gifs) that permit the Company, forexample, to count users who have visited those pages or opened an emailand for other related website statistics (for example, recording thepopularity of a certain section and verifying system and serverintegrity).</li>
        </ul>



        <p>Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain onYour personal computer or mobile device when You go offline, while SessionCookies are deleted as soon as You close Your web browser. </p>



        <p>We use both Session and Persistent Cookies for the purposes set out below:</p>



        <ul>
        <li>Necessary / Essential Cookies Type: Session Cookies Administered by: Us Purpose: These Cookies are essential to provide You with servicesavailable through the Website and to enable You to use some of itsfeatures. They help to authenticate users and prevent fraudulent use ofuser accounts. Without these Cookies, the services that You have asked forcannot be provided, and We only use these Cookies to provide You withthose services.</li>



        <li>Cookies Policy / Notice Acceptance Cookies Type: Persistent Cookies Administered by: Us Purpose: These Cookies identify if users have accepted the use of cookieson the Website.</li>



        <li>Functionality Cookies Type: Persistent Cookies Administered by: Us Purpose: These Cookies allow us to remember choices You make when You usethe Website, such as remembering your login details or languagepreference. The purpose of these Cookies is to provide You with a morepersonal experience and to avoid You having to re-enter your preferencesevery time You use the Website.</li>
        </ul>



        <p>For more information about the cookies we use and your choices regardingcookies, please visit our Cookies Policy or the Cookies section of our PrivacyPolicy.</p>



        <h2 className="text-2xl font-semibold my-3">Use of Your Personal Data</h2>



        <p>The Company may use Personal Data for the following purposes:</p>



        <ul>
        <li>To provide and maintain our Service , including to monitor the usage ofour Service.</li>



        <li>To manage Your Account: to manage Your registration as a user of theService. The Personal Data You provide can give You access to differentfunctionalities of the Service that are available to You as a registereduser.</li>



        <li>For the performance of a contract: the development, compliance andundertaking of the purchase contract for the products, items or servicesYou have purchased or of any other contract with Us through the Service.</li>



        <li>To contact You: To contact You by email, telephone calls, SMS, or otherequivalent forms of electronic communication, such as a mobileapplication’s push notifications regarding updates or informativecommunications related to the functionalities, products or contractedservices, including the security updates, when necessary or reasonable fortheir implementation.</li>



        <li>To provide You with news, special offers and general information aboutother goods, services and events which we offer that are similar to thosethat you have already purchased or enquired about unless You have optednot to receive such information.</li>



        <li>To manage Your requests: To attend and manage Your requests to Us.</li>



        <li>For business transfers: We may use Your information to evaluate or conducta merger, divestiture, restructuring, reorganization, dissolution, orother sale or transfer of some or all of Our assets, whether as a goingconcern or as part of bankruptcy, liquidation, or similar proceeding, inwhich Personal Data held by Us about our Service users is among the assetstransferred.</li>



        <li>For other purposes : We may use Your information for other purposes, suchas data analysis, identifying usage trends, determining the effectivenessof our promotional campaigns and to evaluate and improve our Service,products, services, marketing and your experience.</li>
        </ul>



        <p>We may share Your personal information in the following situations:</p>



        <ul>
        <li>With Service Providers: We may share Your personal information withService Providers to monitor and analyze the use of our Service, tocontact You.</li>



        <li>For business transfers: We may share or transfer Your personal informationin connection with, or during negotiations of, any merger, sale of Companyassets, financing, or acquisition of all or a portion of Our business toanother company.</li>



        <li>With Affiliates: We may share Your information with Our affiliates, inwhich case we will require those affiliates to honor this Privacy Policy.Affiliates include Our parent company and any other subsidiaries, jointventure partners or other companies that We control or that are undercommon control with Us.</li>



        <li>With business partners: We may share Your information with Our businesspartners to offer You certain products, services or promotions.</li>



        <li>With other users: when You share personal information or otherwiseinteract in the public areas with other users, such information may beviewed by all users and may be publicly distributed outside.</li>



        <li>With Your consent : We may disclose Your personal information for anyother purpose with Your consent.</li>
        </ul>



        <h2 className="text-2xl font-semibold my-3">Retention of Your Personal Data</h2>



        <p>The Company will retain Your Personal Data only for as long as is necessaryfor the purposes set out in this Privacy Policy. We will retain and use YourPersonal Data to the extent necessary to comply with our legal obligations(for example, if we are required to retain your data to comply with applicablelaws), resolve disputes, and enforce our legal agreements and policies.</p>



        <p>The Company will also retain Usage Data for internal analysis purposes. UsageData is generally retained for a shorter period of time, except when this datais used to strengthen the security or to improve the functionality of OurService, or We are legally obligated to retain this data for longer timeperiods.</p>



        <h2 className="text-2xl font-semibold my-3">Transfer of Your Personal Data</h2>



        <p>Your information, including Personal Data, is processed at the Company’soperating offices and in any other places where the parties involved in theprocessing are located. It means that this information may be transferred to —and maintained on — computers located outside of Your state, province, countryor other governmental jurisdiction where the data protection laws may differthan those from Your jurisdiction.</p>



        <p>Your consent to this Privacy Policy followed by Your submission of suchinformation represents Your agreement to that transfer.</p>



        <p>The Company will take all steps reasonably necessary to ensure that Your datais treated securely and in accordance with this Privacy Policy and no transferof Your Personal Data will take place to an organization or a country unlessthere are adequate controls in place including the security of Your data andother personal information.</p>



        <h2 className="text-2xl font-semibold my-3">Delete Your Personal Data</h2>



        <p>You have the right to delete or request that We assist in deleting thePersonal Data that We have collected about You.</p>



        <p>Our Service may give You the ability to delete certain information about Youfrom within the Service.</p>



        <p>You may update, amend, or delete Your information at any time by signing in toYour Account, if you have one, and visiting the account settings section thatallows you to manage Your personal information. You may also contact Us torequest access to, correct, or delete any personal information that You haveprovided to Us.</p>



        <p>Please note, however, that We may need to retain certain information when wehave a legal obligation or lawful basis to do so.</p>



        <h2 className="text-2xl font-semibold my-3">Disclosure of Your Personal Data</h2>



        <p>Business Transactions</p>



        <p>If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your Personal
        Data is transferred and becomes subject to a different Privacy Policy.

        Law enforcement  
        ~~~~~~~~~~~~~~~

        Under certain circumstances, the Company may be required to disclose Your
        Personal Data if required to do so by law or in response to valid requests by
        public authorities (e.g. a court or a government agency).

        Other legal requirements  </p>



        <p>~~~</p>



        <p>The Company may disclose Your Personal Data in the good faith belief that suchaction is necessary to:</p>



        <ul>
        <li>Comply with a legal obligation</li>



        <li>Protect and defend the rights or property of the Company</li>



        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>



        <li>Protect the personal safety of Users of the Service or the public</li>



        <li>Protect against legal liability</li>
        </ul>



        <h2 className="text-2xl font-semibold my-3">Security of Your Personal Data</h2>



        <p>The security of Your Personal Data is important to Us, but remember that nomethod of transmission over the Internet, or method of electronic storage is100% secure. While We strive to use commercially acceptable means to protectYour Personal Data, We cannot guarantee its absolute security.</p>



        <h1 className="text-3xl font-bold my-4">Children’s Privacy</h1>



        <p>Our Service does not address anyone under the age of 13. We do not knowinglycollect personally identifiable information from anyone under the age of 13.If You are a parent or guardian and You are aware that Your child has providedUs with Personal Data, please contact Us. If We become aware that We havecollected Personal Data from anyone under the age of 13 without verificationof parental consent, We take steps to remove that information from Ourservers.</p>



        <p>If We need to rely on consent as a legal basis for processing Your informationand Your country requires consent from a parent, We may require Your parent’sconsent before We collect and use that information.</p>



        <h1 className="text-3xl font-bold my-4">Links to Other Websites</h1>



        <p>Our Service may contain links to other websites that are not operated by Us.If You click on a third party link, You will be directed to that third party’ssite. We strongly advise You to review the Privacy Policy of every site Youvisit.</p>



        <p>We have no control over and assume no responsibility for the content, privacypolicies or practices of any third party sites or services.</p>



        <h1 className="text-3xl font-bold my-4">Changes to this Privacy Policy</h1>



        <p>We may update Our Privacy Policy from time to time. We will notify You of anychanges by posting the new Privacy Policy on this page.</p>



        <p>We will let You know via email and/or a prominent notice on Our Service, priorto the change becoming effective and update the “Last updated” date at the topof this Privacy Policy.</p>



        <p>You are advised to review this Privacy Policy periodically for any changes.Changes to this Privacy Policy are effective when they are posted on thispage.</p>



        <h1 className="text-3xl font-bold my-4">Contact Us</h1>



        <p>If you have any questions about this Privacy Policy, You can contact us:</p>



        <ul>
        <li>By email: info@infrafoam.in</li>



        <li>By visiting this page on our website: <Link to={'/contact'} >https://infrafoam.in/contact-us/</Link></li>
        </ul>
        </div>
      
    </>
  )
}

export default Privacypolicy
